### ISSUE TITLE
Day of events considered to be passed

### ISSUE THREAD

**Issue by joelworsham** [stuttter/wp-event-calendar#2] opened 2015-11-04 15:26 UTC
I've noticed that if it is the currently the date of an event's end date, it is considered to be passed. It seems to me that it would make more sense to not consider an event to be passed until the day after.

**Comment by JJJ** [comment] 2015-12-30 23:29
That's true. I'll try to fix this in the next release (0.2.2)

**Comment by JJJ** [comment] 2016-03-30 19:50
I _think_ this is fixed in 0.3.0, as I ran into this organically myself.

There is some goofy logic in place for `strtotime()` that makes the "last week" vs. "this week" act funny on Sundays, depending on the time of day that it is. Sigh.

Please reopen if this is not fixed, and I'll take another look. When you do, if you can include any relevant timezone settings for PHP/WordPress/Server, that would help me narrow down the cause.

Thanks @joelworsham!

**Closed as completed by JJJ** 2016-03-30 19:50 UTC
Labels: bug

**Comment by joelworsham** [comment] 2016-03-30 20:55
Thanks man. I'll check into this at some point.

:+1:
